---
layout: post
title: "pytest7.4版本的一个变更，可能会影响你的项目"
date: "2023-07-11T01:16:55.021Z"
---
pytest7.4版本的一个变更，可能会影响你的项目
==========================

pytest7.4版本的一个变更，可能会影响你的项目
==========================

> 本文撰写于 2023.7.10

准备工作
====

*   项目结构如下
    
        D:\Gitee\DemoRepo (17.97MB)
        +-- testCases (1.03KB)
        |   +-- conftest.py (252b)
        |   +-- pmCases (574b)
        |   |   +-- conftest.py (259b)
        |   |   `-- test_logout.py (315b)
        
    
*   顶层conftest.py内容
    
        import pytest
        
        @pytest.fixture(scope='session')
        def fix_all():
            print('fix_all')
        
    
*   pmCases下的conftest.py内容
    
        import pytest
        
        @pytest.fixture(scope='session', autouse=True)
        def fix_all2():
            print('fix_all2')
        
        
    
*   test\_logout.py内容
    
        import pytest
        
        
        def test_logout(fix_all):
            print('test_logout')
        
        if __name__ == '__main__':
            pytest.main(['-sv',__file__])
        
    

Pytest7.4之前
===========

> 用的Pytest7.3.1，而实际7.4.0之前也就只有一个7.3.2了

*   你是可以执行test\_logout.py的
    
*   效果如下
    
        test_logout.py::test_logout fix_all2
        fix_all
        test_logout
        PASSED
        
    
*   所以按照以前的认识
    
    *   conftest可以存在多个
    *   测试用例可以看到上级目录的conftest
    *   但看不到下级目录的conftest(此处没有演示)

Pytest4.0
=========

执行效果
----

> 注意把pytest更新到pytest7.4.0

*   同样执行test\_logout.py
    
*   效果如下
    
        D:\Gitee\DemoRepo\venv\Scripts\python.exe D:/Gitee/DemoRepo/testCases/pmCases/test_logout.py
        ============================= test session starts =============================
        platform win32 -- Python 3.9.6, pytest-7.4.0, pluggy-1.2.0 -- D:\Gitee\DemoRepo\venv\Scripts\python.exe
        cachedir: .pytest_cache
        rootdir: D:\Gitee\DemoRepo\testCases\pmCases
        collecting ... collected 1 item
        
        test_logout.py::test_logout fix_all2
        ERROR
        
        =================================== ERRORS ====================================
        ________________________ ERROR at setup of test_logout ________________________
        file D:\Gitee\DemoRepo\testCases\pmCases\test_logout.py, line 10
          def test_logout(fix_all):
        E       fixture 'fix_all' not found
        >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, fix_all2, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
        >       use 'pytest --fixtures [testpath]' for help on them.
        
        D:\Gitee\DemoRepo\testCases\pmCases\test_logout.py:10
        =========================== short test summary info ===========================
        ERROR test_logout.py::test_logout
        ============================== 1 error in 0.01s ===============================
        
        进程已结束，退出代码为 0
        
        
    
*   很清楚的提示
    
        E       fixture 'fix_all' not found
        
    
*   子目录无法去引用上级目录的fixture
    
*   而同级目录不受影响
    
*   我们的实战课就会用到子目录下的测试文件调用上级目录的fixture，是没问题的，但现在会受影响。
    
*   这是为何呢？第一个想法就是版本变动了。但觉得不太可以理解，正常版本变动对这些逻辑不应该去大改，除非是大版本的改变。因为一旦出现这样的引用，你以前的项目会无法调用。
    

* * *

*   很多的时候你是在终端下执行
    
*   修改test\_logout.py
    
        def test_logout(fix_all):
            print('test_logout')
        
    
*   终端下执行
    
        D:\Gitee\DemoRepo\testCases>pytest
        # 这是成功的
        
    
*   这样执行
    
        D:\Gitee\DemoRepo\testCases\pmCases>pytest
        # 报错跟上面一样  E       fixture 'fix_all' not found
        
        
    
*   基于此，如果你是终端下执行的话，其实是没啥影响的。
    
*   只有你要在子目录下测试或者单独执行子测试用例时可能会有问题
    

* * *

*   带着这样的疑问去官方文档找原因。

changlog Of pytest 7.4.0
------------------------

> [https://docs.pytest.org/en/7.4.x/changelog.html#](https://docs.pytest.org/en/7.4.x/changelog.html#)

**发布时间 (2023-06-23)**

### Features

*   [#10901](https://github.com/pytest-dev/pytest/issues/10901): Added [`ExceptionInfo.from_exception()`](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.ExceptionInfo.from_exception), a simpler way to create an [`ExceptionInfo`](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.ExceptionInfo) from an exception. This can replace [`ExceptionInfo.from_exc_info()`](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.ExceptionInfo.from_exc_info) for most uses.

### Improvements

*   [#10872](https://github.com/pytest-dev/pytest/issues/10872): Update test log report annotation to named tuple and fixed inconsistency in docs for [`pytest_report_teststatus`](https://docs.pytest.org/en/7.4.x/reference/reference.html#std-hook-pytest_report_teststatus) hook.
    
*   [#10907](https://github.com/pytest-dev/pytest/issues/10907): When an exception traceback to be displayed is completely filtered out (by mechanisms such as `__tracebackhide__`, internal frames, and similar), now only the exception string and the following message are shown:
    
    “All traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames.”.
    
    Previously, the last frame of the traceback was shown, even though it was hidden.
    
*   [#10940](https://github.com/pytest-dev/pytest/issues/10940): Improved verbose output (`-vv`) of `skip` and `xfail` reasons by performing text wrapping while leaving a clear margin for progress output.
    
    Added `TerminalReporter.wrap_write()` as a helper for that.
    
*   [#10991](https://github.com/pytest-dev/pytest/issues/10991): Added handling of `%f` directive to print microseconds in log format options, such as `log-date-format`.
    
*   [#11005](https://github.com/pytest-dev/pytest/issues/11005): Added the underlying exception to the cache provider’s path creation and write warning messages.
    
*   [#11013](https://github.com/pytest-dev/pytest/issues/11013): Added warning when [`testpaths`](https://docs.pytest.org/en/7.4.x/reference/reference.html#confval-testpaths) is set, but paths are not found by glob. In this case, pytest will fall back to searching from the current directory.
    
*   [#11043](https://github.com/pytest-dev/pytest/issues/11043): When `--confcutdir` is not specified, and there is no config file present, the conftest cutoff directory (`--confcutdir`) is now set to the [rootdir](https://docs.pytest.org/en/7.4.x/reference/customize.html#rootdir). Previously in such cases, `conftest.py` files would be probed all the way to the root directory of the filesystem. If you are badly affected by this change, consider adding an empty config file to your desired cutoff directory, or explicitly set `--confcutdir`.
    
*   [#11081](https://github.com/pytest-dev/pytest/issues/11081): The [`norecursedirs`](https://docs.pytest.org/en/7.4.x/reference/reference.html#confval-norecursedirs) check is now performed in a [`pytest_ignore_collect`](https://docs.pytest.org/en/7.4.x/reference/reference.html#std-hook-pytest_ignore_collect) implementation, so plugins can affect it.
    
    If after updating to this version you see that your `norecursedirs` setting is not being respected, it means that a conftest or a plugin you use has a bad `pytest_ignore_collect` implementation. Most likely, your hook returns `False` for paths it does not want to ignore, which ends the processing and doesn’t allow other plugins, including pytest itself, to ignore the path. The fix is to return `None` instead of `False` for paths your hook doesn’t want to ignore.
    
*   [#8711](https://github.com/pytest-dev/pytest/issues/8711): [`caplog.set_level()`](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.LogCaptureFixture.set_level) and [`caplog.at_level()`](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.LogCaptureFixture.at_level) will temporarily enable the requested `level` if `level` was disabled globally via `logging.disable(LEVEL)`.
    

### Bug Fixes

*   [#10831](https://github.com/pytest-dev/pytest/issues/10831): Terminal Reporting: Fixed bug when running in `--tb=line` mode where `pytest.fail(pytrace=False)` tests report `None`.
*   [#11068](https://github.com/pytest-dev/pytest/issues/11068): Fixed the `--last-failed` whole-file skipping functionality (“skipped N files”) for [non-python test files](https://docs.pytest.org/en/7.4.x/example/nonpython.html#non-python-tests).
*   [#11104](https://github.com/pytest-dev/pytest/issues/11104): Fixed a regression in pytest 7.3.2 which caused to [`testpaths`](https://docs.pytest.org/en/7.4.x/reference/reference.html#confval-testpaths) to be considered for loading initial conftests, even when it was not utilized (e.g. when explicit paths were given on the command line). Now the `testpaths` are only considered when they are in use.
*   [#1904](https://github.com/pytest-dev/pytest/issues/1904): Fixed traceback entries hidden with `__tracebackhide__ = True` still being shown for chained exceptions (parts after “… the above exception …” message).
*   [#7781](https://github.com/pytest-dev/pytest/issues/7781): Fix writing non-encodable text to log file when using `--debug`.

### Improved Documentation

*   [#9146](https://github.com/pytest-dev/pytest/issues/9146): Improved documentation for [`caplog.set_level()`](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.LogCaptureFixture.set_level).

### Trivial/Internal Changes

*   [#11031](https://github.com/pytest-dev/pytest/issues/11031): Enhanced the CLI flag for `-c` to now include `--config-file` to make it clear that this flag applies to the usage of a custom config file.

抓重点
---

*   原文
    
        When `--confcutdir` is not specified, and there is no config file present, the conftest cutoff directory (`--confcutdir`) is now set to the [rootdir](https://docs.pytest.org/en/7.4.x/reference/customize.html#rootdir). Previously in such cases, `conftest.py` files would be probed all the way to the root directory of the filesystem. If you are badly affected by this change, consider adding an empty config file to your desired cutoff directory, or explicitly set `--confcutdir`.
        
    
*   译文
    
        当未指定--confcutdir并且没有配置文件存在时，conftest截断目录(--confcutdir)现在被设置为rootdir。在以前的情况下，conftest.py文件会一直被探测到文件系统的根目录。如果你受到这个变化的严重影响，考虑在所需的截断目录中添加一个空的配置文件，或者明确地设置--confcutdir。
        
    

解决方式
----

*   指定参数--confcutdir
    
*   示例1: test\_logout.py执行
    
        import pytest
        
        
        def test_logout(fix_all):
            print('test_logout')
        
        if __name__ == '__main__':
            pytest.main(['-sv','--confcutdir=..',__file__]) # 意思是设定conftest.py的搜索根目录是当前目录上级
        
    
*   示例2: 终端执行
    
        # 你在pmCases下执行
        # 如果在项目根目录下，本来就是ok的
        pytest --confcutdir=..
        
    
*   示例3: pytest.ini
    
        [pytest]
        # 改为实际的项目根目录即可
        addopts = --confcutdir="D:\Gitee\DemoRepo" 
        
    
    *   注意不要写成`--confcutdir=.`(因为你是把pytest.ini放在根目录下的)

补充说明
----

*   截止到撰写本文的时候(2023-7-10)发现
    
*   pip install pytest会安装最新的Pytest7.4.0
    
*   而通过pycharm安装则是Pytest7.3.1
    
*   对于这个参数，命令行--help的解释是
    
          --confcutdir=dir      Only load conftest.py's relative to specified dir