---
layout: post
title: "Java基础——异常"
date: "2023-07-09T01:41:08.787Z"
---
Java基础——异常
==========

为什么需要异常
-------

### 引出

    public static void main(String[] args) {
            int a = 10;
            int b = 0;
            int number = a / b;
            System.out.println("程序继续向下运行");
    }
    

上面的代码运行时会报如下的错，意思是分母为0异常。

    Exception in thread "main" java.lang.ArithmeticException: / by zero
    

### 解决

一段Java代码，如果遇到了不算致命的错误，就停止运行，这就不符合实际需求，不好。这时候对可能发生异常的代码进行try-catch处理，保证程序即使遇到异常，也能继续向下运行。代码改进如下：（可能还是有点懵，下面有具体对异常处理的介绍）

     public static void main(String[] args) {
            int a = 10;
            int b = 0;
            try {
                int number = a / b;
            } catch (Exception exception) {
                //exception.printStackTrace();
                System.out.println("出现异常的原因-->"+exception.getMessage());//输出异常信息
            }
            System.out.println("程序继续向下运行");
      }
    

### 异常介绍

#### 概念

异常指不期而至的各种状况，如：文件找不到、网络连接失败、非法参数等。异常是一个事件，它发生在程序运行期间，干扰了正常的指令流程。（开发过程中的语法错误和逻辑错误不是异常）

#### Java异常类层次结构图

![image-20230709010214757](https://img2023.cnblogs.com/blog/2355908/202307/2355908-20230709011021757-1878127762.png)

#### 分类

1.Error(错误)：Error是严重错误，程序会崩溃。此类错误一般表示代码运行时 JVM 出现问题。通常有 Virtual MachineError（虚拟机运行错误）、NoClassDefFoundError（类定义错误）等。比如 OutOfMemoryError：内存不足错误；StackOverflowError：栈溢出错误。此类错误发生时，JVM 将终止线程。这些错误是不受检异常，非代码性错误。因此，当此类错误发生时，应用程序不应该去处理此类错误。按照Java惯例，我们是不应该实现任何新的Error子类的！

2.Exception：其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如空指针访问，试图读取不存在的文件，网络连接中  
断等等。又可以分为两类：

##### 运行时异常

程序运行时，发生的异常.一般是指编程时的逻辑错误，是程序员应该避免其出现的异常。java.lang.RuntimeException类及它的子类都是运行时异常.对于运行时异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响

##### 编译时异常

编程时，编译器检查出的异常.是编译器要求必须处置的异常。

#### 常见运行时异常

1.NullPointerException 空指针异常

2.ArithmeticException 数学运算异常

3.ArrayIndexOutOfBoundsException 数组下标越界异常

4.ClassCastException 类型转换异常

5.NumberFormatException 数字格式不正确异常

举例

1.NullPointerException空指针异常

当应用程序试图在需要对象的地方使用null时，抛出该异常，看下面的代码举例。

    public static void main(String[] args) {
            String name = null;
            System.out.println(name.length());
    }
    

报如下异常：

![image-20230706121148044](https://img2023.cnblogs.com/blog/2355908/202307/2355908-20230709011021158-459882952.png)

2.ArithmeticException数学运算异常

当出现异常的运算条件时，抛出此异常。例如，一个整数“除以零”时，抛出此类的一个实例，前面引出的例子就是这种情况，不重复了。3.ArrayIndexOutOfBoundsException数组下标越界异常

用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小，则该索引为非法索引

    public static void main(String[] args) {
            int[] arr = {1,2,3};
            for (int i = 0; i <= arr.length; i++) {
                System.out.println(arr[i]);
            }
    }
    

报如下异常：

![image-20230706121856480](https://img2023.cnblogs.com/blog/2355908/202307/2355908-20230709011020599-2071077462.png)

4.ClassCastException类型转换异常

当试图将对象强制转换为不是实例的子类时，抛出该异常。

    public class ClassCastException {
        public static void main(String[] args) {
            A b = new B();
            B b2 = (B) b;
            C c2 = (C) b;//这里抛出ClassCastException
        }
    }
    class A{}
    class B extends A{}
    class C extends A{}
    

报如下异常：

![image-20230706122536756](https://img2023.cnblogs.com/blog/2355908/202307/2355908-20230709011020157-1121909746.png)

5.NumberFormatException数字格式不正确异常

当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常

     public static void main(String[] args) {
            String name = "啊啊啊啊啊";
            int num = Integer.parseInt(name);
     }
    

报如下异常：

![image-20230706121547800](https://img2023.cnblogs.com/blog/2355908/202307/2355908-20230709011019553-1504365426.png)

#### 常见编译时异常

1.SQLException //操作数据库时，查询表可能发生异常  
2.IOException //操作文件时，发生的异常  
3.FileNotFoundException //当操作一个不存在的文件时，发生异常  
4.ClassNotFoundException //加载类，而该类不存在时，异常  
5.EOFException //操作文件，到文件末尾，发生异常  
6.illegalArguementException //参数异常

### 异常处理

#### 方式

1.try-catch-finally  
程序员在代码中捕获发生的异常，自行处理  
2.throws  
将发生的异常抛出，交给调用者（方法）来处理，最顶级的处理者就是JVM

#### try-catch-finally

##### 说明

try块用于包含可能出错的代码。catch块用于处理try块中发生的异常。可以根据需要在程序中有多个try......catch块。finally可有可没有，这个代码块的内容要求不管try代码块是否有异常发生，始终要执行finally所以，通常将释放资源的代码，放在finally。

##### 语法

    try {
               //可疑代码
    			//将异常生成对应的异常对象，传递给catch块
            } catch (Exception exception) {
                //对异常的处理
            }finally {
             //无论异常有没有发生，都要执行的业务代码（可选）   
      }
    

##### 举例

     public static void main(String[] args) {
            int a = 10;
            int b = 0;
            try {
                int number = a / b;
            } catch (Exception exception) {
                //exception.printStackTrace();
                System.out.println("出现异常的原因-->"+exception.getMessage());//输出异常信息
            }
            System.out.println("程序继续向下运行");
      }
    

##### 注意事项

1.如果异常发生了，则异常发生后面的代码不会执行，直接进入到catch块

2.如果异常没有发生，则顺序执行try的代码块，不会进入到catch.

3.如果希望不管是否发生异常，都执行某段代码（比如关闭连接，释放资源等）则使用代码-finally{}

4.可以有多个catch语句，捕获不同的异常（进行不同的业务处理），要求父类异常在后，子类异常在前，比如(Exception在后，NullPointerException在前)，如果发生异常，只会匹配一个catch,案例演示

    public class TryCatchDetail {
        public static void main(String[] args) {
            try {
                Person person = new Person();
                System.out.println(person.getName());//如果这里的名字为空，那么就会发生空指针异常。
                int a = 10;
                int b = 0;
                int res = a / b;
            } catch (NullPointerException e) {
                System.out.println("空指针异常="+e.getMessage());
            }catch (ArithmeticException e){
                System.out.println("算术异常="+e.getMessage());
            }catch (Exception e){
                System.out.println(e.getMessage());
            }
            finally {
            }
        }
    }
    class Person{
        private String name = "jack";
        public String getName(){
            return name;
        }
    }
    

5.可以进行try-finally配合使用，这种用法相当于没有捕获异常，因此程序会直接崩掉/退出。应用场景，就是执行一段代码，不管是否发生异常，都必须执行某个业务逻辑

     public static void main(String[] args) {
            try {
                int a = 10;
                int b = 0;
                int res = a / b;
            } finally {
                System.out.println("执行了finally.....");
            }
            System.out.println("程序继续执行.....");
      }
    

##### 小结

1.如果没有出现异常，则执行try块中所有语句，不执行catch块中语句，如果有finally,最后还需要执行finally里面的语句  
2.如果出现异常，则try块中异常发生后，try块剩下的语句不再执行。将执行catch块中的语句，如果有finally,最后还需要执行finally里面的语句！

#### throws

##### 说明

1.如果一个方法（中的语句执行时）可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。

2.在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。

##### 举例

    public static void readFile(String file)throws FileNotFoundException {
            //读文件的操作可能产生FileNotFoundException类型的异常
            FilelnputStream fis = new FilelnputStream("d://aa.txt");
    }
    

##### 注意事项

1.对于编译异常，程序中必须处理，比如try-catch或者throws

2.对于运行时异常，程序中如果没有处理，默认就是throws的方式处理

3.子类重写父类的方法时，对抛出异常的规定：子类重写的方法，所抛出的异常类型要么和父类抛出的异常一致，要么为父类抛出的异常的类型的子类型

4.在throws过程中，如果有方法try-catch,就相当于处理异常，就可以不必throws

#### 自定义异常

##### 概念

当程序中出现了某些“"错误”，但该错误信息并没有在Throwable子类中描述处理，这个时候可以自己设计异常类，用于描述该错误信息。

##### 步骤

1.定义类：自定义异常类名（程序员自己写）继承Exception或RuntimeException  
2.如果继承Exception,属于编译异常  
3.如果继承RuntimeException,属于运行异常（一般来说，继承RuntimeException)

##### 举例

要求：当我们接收Person对象年龄时，要求范围在18-120之间，否则抛出一个自定义异常（要求继承RuntimeException),并给出提示信息

    public class CustomException {
        public static void main(String[] args) {
            int age = 180;
            //要求范围在18-120之间，否则抛出一个自定义异常
            if (!(age >= 18 && age <= 120)){
                //这里我们可以通过构造器，设置信息
                throw new AgeException("年龄需要在18~120岁之间");
            }
            System.out.println("你的年龄范围正确");
        }
    }
    //自定义一个异常
    /**
     * 1.一般情况下，我们自定义异常是继承RuntimeException
     * 2.即把自定义异常做成运行时异常，好处时，我们可以使用默认的处理机制
     * 3.即比较方便
     */
    class AgeException extends RuntimeException{
        public AgeException(String message){
            super(message);
        }
    }
    

### throw和throws的区别

意义

位置

后面跟的东西

throws

异常处理的一种方式

方法声明处

异常类型

throw

手动生成异常对象的关键字

方法体中

异常对象